### ISSUE TITLE
[Bug]: FTB menu overlap

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/barteringstation#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

When using the Bartering station with FTB Chunks, the top left corner FTB buttons are places on the Bartering station UI
![image](https://user-images.githubusercontent.com/44974827/195909584-2caff514-8ccc-4d52-94d1-af7827db395a.png)

**Comment by Fuzss** [comment]
Should be fixed in v4.0.1. Please reopen if it's not.
