### ISSUE TITLE
[Crash]: [crash-2024-06-03_22.35.07-client.txt]

### ISSUE THREAD

**Issue by aruearoe** [Fuzss/barteringstation#11]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

BarteringStation-v8.0.0-1.20.1-Fabric.jar

### Minimal Setup

⸺

### Notes (Required)

Can someone who can solve this problem help me? Please.

**[crash-2024-06-03_22.35.07-client.txt](https://github.com/user-attachments/files/15534695/crash-2024-06-03_22.35.07-client.txt)**

- cardinal-components-api-5.2.2
- BarteringStation-v8.0.0-1.20.1-Fabric.jar
- fabric-api-0.92.2+1.20.1.jar
- ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
- PuzzlesLib-v8.1.20-1.20.1-Fabric

### Crash Report (Required)

https://github.com/user-attachments/files/15534695/crash-2024-06-03_22.35.07-client.txt

### latest.log (Optional)

https://github.com/user-attachments/files/15534791/latest.log

**Comment by Fuzss** [comment]
Report to movingelevators.
