### ISSUE TITLE
[Crash]: MC crashes when entering the nether

### ISSUE THREAD

**Issue by Cape-City** [Fuzss/barteringstation#6]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

Bartering: v5.0.0 / PuzzleLib: v5.0.28

### Notes (Required)

When entering the nether where the batering station is placed, the world crashes:

![grafik](https://github.com/Fuzss/barteringstation/assets/122229367/1b60a082-b790-4c7e-bc52-5ed25f6a5cdc)

Again after rollback to PuzzlesLib-v5.0.24-1.19.3-Fabric.jar i was able to load into my world normally.

### Crash Report (Required)

https://gist.github.com/Cape-City/abe19587451cf50044df1aef8b30c347

### latest.log (Optional)

https://gist.github.com/Cape-City/373208e3f331570f19a43fd6ffd419ad

**Comment by Fuzss** [comment]
Thanks, fixed in v5.0.30. Also reverted a few other changes from v5.0.25, was a bit too quick with applying some of the refactors planned for 1.19.4.

**Comment by Cape-City** [comment]
I love your mods - so many great ideas, which brings so much fun within the gameplay! Can't even say which one i love the most!

**Comment by Fuzss** [comment]
Thank you so much, really means a lot! My favorite definitely is Enchanting Infuser. :)

**Comment by Cape-City** [comment]
I will try this mod also ;) the working bench and enchantment table, where icons flying around looks amazing! The diagonal fences, for better builds are wonderful too... today i tested the hang glider - it's a cool alternative for the elytra, just to come smooth from any mountains like in Zelda BOTW, if you where able to place it into the elytra slot and it would be automaticly doing its thing, when pressing space in the air - falling down somewhere is no nightmare again ;)
